### ISSUE TITLE
Kubeproxy pod missing parameter with addnode.py

### ISSUE THREAD

**Issue by JesseVS** [pblaas/nagoya#1]
I added a node with the following command:
```bash
./addnode.py --workerimageflavor 2012 192.168.3.x
terraform apply
```
The node added itself to the cluster, but the kube-proxy pod kept crashing.
I noticed it missed a value at the Commands section:
```yaml
/hyperkube
proxy
--master=https://192.168.3.3
--cluster-cidr=10.244.0.0/16
--conntrack-max-per-core=0
--kubeconfig=/etc/kubernetes/master-kubeconfig.yaml
--v=
```
Which should be:
```yaml

/hyperkube
proxy
--master=https://192.168.3.3
--cluster-cidr=10.244.0.0/16
--conntrack-max-per-core=0
--kubeconfig=/etc/kubernetes/master-kubeconfig.yaml
--v=1
```
It was missing the 1 at the --v variable.
I added the 1 at node_{ip}.yaml and .json file and did 
```bash
terraform apply
```

again and then it worked.

**Comment by pblaas** [comment]
Thanks for catching that. Will start on a fix for this.

**Comment by pblaas** [comment]
Merged fix from development branch to Master.
